env:
  browser: true
  jquery: true
  es6: true
extends: 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
plugins:
  - react
rules:
  react/jsx-uses-vars: 1
  react/jsx-uses-react: 1
  no-console:
    - error
    -
      allow:
        - warn
        - error
  no-unused-vars:
    - error
    -
      vars: local
      args: none
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  comma-dangle:
    - 2
    - always-multiline
  no-multiple-empty-lines:
    - 2
    - max: 2
  semi:
    - error
    - always
  keyword-spacing:
    - error
    - before: true
  space-before-function-paren:
    - 2
    -
      anonymous: always
      named: never
  yoda:
    - 2
    - always
  global-require: error
  space-before-blocks: error
  space-infix-ops: error
globals:
  require: false
  define: false
  module: false
  download: true
