env:
  browser: true
  jquery: true
  es6: true
extends:
  - 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
plugins:
  - react
settings:
  react:
    version: '15.5.4'
rules:
  react/jsx-uses-vars: 1
  react/jsx-uses-react: 1
  react/prefer-es6-class:
    - 1
    - always
  react/jsx-indent:
    - error
    - 2
  react/jsx-indent-props:
    - error
    - 2
  react/jsx-curly-spacing:
    - error
    - never
  react/jsx-equals-spacing:
    - error
    - never
  react/jsx-space-before-closing:
    - error
    - always
  react/no-deprecated:
    - error
  react/no-unknown-property:
    - 1
  react/no-find-dom-node:
    - 1
  react/jsx-boolean-value:
    - 1
    - never
  no-console:
    - error
    -
      allow:
        - warn
        - error
  no-unused-vars:
    - error
    -
      vars: local
      args: none
  no-self-compare:
    - error
  space-unary-ops:
    - error
    -
      words: true
      nonwords: false
  space-in-parens:
    - error
    - never
  spaced-comment:
    - error
    - always
  no-tabs:
    - error
  indent:
    - error
    - 2
    -
      SwitchCase: 1
      MemberExpression: 1
      ObjectExpression: 1
      VariableDeclarator: 1
      outerIIFEBody: 0
  linebreak-style:
    - error
    - unix
  eol-last:
    - error
    - always
  unicode-bom:
    - error
    - never
  no-trailing-spaces:
    - error
  array-bracket-spacing:
    - error
    - never
  object-curly-spacing:
    - error
    - never
  key-spacing:
    - error
    - align: value
  comma-spacing:
    - error
  block-spacing:
    - error
  computed-property-spacing:
    - error
    - never
  func-call-spacing:
    - error
    - never
  no-multi-spaces:
    - error
    - exceptions:
        Property: true
        VariableDeclarator: true
  curly:
    - error
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  quotes:
    - error
    - single
  comma-dangle:
    - error
    - always-multiline
  no-multiple-empty-lines:
    - error
    - max: 2
  semi:
    - error
    - always
  keyword-spacing:
    - error
    - before: true
  space-before-function-paren:
    - error
    -
      anonymous: always
      named: never
  no-extra-parens:
    - error
    - all
    - ignoreJSX: all
  no-lonely-if:
    - error
  yoda:
    - error
    - always
  global-require: error
  space-before-blocks: error
  space-infix-ops: error
globals:
  require: false
  define: false
  module: false
  download: true
  alertify: true
