env:
  browser: true
  jquery: true
extends: 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
plugins:
  - react
rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  comma-dangle:
    - 2
    - always-multiline
  no-multiple-empty-lines:
    - 2
    - max: 2
  semi:
    - error
    - always
  keyword-spacing:
    - error
    - before: true
  space-before-function-paren:
    - 2
    -
      anonymous: always
      named: never
  yoda:
    - 2
    - always
  global-require: error
globals:
  require: false
  define: false
  module: false
