SSH_key: ./server-key.ppk
rsync:
 - '--include'
 - ' "js/bundle.js"'
 - '--exclude'
 - ' "js/*"'
 - '--exclude'
 - ' "node_modules"'
host: 'deploy@127.0.0.1:22'
src: '../web/*'
dest: /var/www/html/spa
baseURL: 'https://api.nubity.com'
